# Generated by Django 5.2.3 on 2025-07-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Inbox',
        ),
        migrations.AlterModelTable(
            name='inbox',
            table='inboxes',
        ),
    ]
