# Generated by Django 5.1.5 on 2025-03-01 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='BankFileImport',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('file_name', models.CharField(max_length=255)),
                        ('file_type', models.CharField(choices=[('UNICREDIT_BANK_ACCOUNT_CSV_EXPORT', 'Unicredit Bank Account Csv Export'), ('FINECO_BANK_ACCOUNT_XLSX_EXPORT', 'Fineco Bank Account Xslx Export'), ('UNICREDIT_DEBIT_CARD_CSV_EXPORT', 'Unicredit Debit Card Csv Export')], default='UNICREDIT_BANK_ACCOUNT_CSV_EXPORT', max_length=255)),
                        ('bank_file', models.FileField(upload_to='uploads/')),
                        ('import_date', models.DateTimeField(auto_now_add=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'bank_file_imports',
                    },
                ),
                migrations.CreateModel(
                    name='YnabCategory',
                    fields=[
                        ('id', models.UUIDField(primary_key=True, serialize=False)),
                        ('name', models.CharField(max_length=256)),
                        ('hidden', models.BooleanField()),
                        ('category_group_name', models.CharField(max_length=1024)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'ynab_categories',
                    },
                ),
                migrations.CreateModel(
                    name='YnabImport',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('execution_datetime', models.DateTimeField()),
                        ('server_knowledge', models.IntegerField(blank=True, null=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'ynab_imports',
                    },
                ),
                migrations.CreateModel(
                    name='YnabTransaction',
                    fields=[
                        ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                        ('date', models.DateField()),
                        ('amount', models.FloatField()),
                        ('memo', models.CharField(blank=True, max_length=512, null=True)),
                        ('approved', models.BooleanField()),
                        ('cleared', models.CharField(choices=[('cleared', 'Cleared'), ('uncleared', 'Uncleared'), ('reconciled', 'Reconciled')], max_length=10)),
                        ('flag_color', models.CharField(blank=True, choices=[('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple')], max_length=6, null=True)),
                        ('flag_name', models.CharField(blank=True, max_length=64, null=True)),
                        ('account_id', models.UUIDField(blank=True, null=True)),
                        ('payee_id', models.UUIDField(blank=True, null=True)),
                        ('category_id', models.UUIDField(blank=True, null=True)),
                        ('transfer_account_id', models.UUIDField(blank=True, null=True)),
                        ('transfer_transaction_id', models.CharField(blank=True, max_length=64, null=True)),
                        ('matched_transaction_id', models.CharField(blank=True, max_length=64, null=True)),
                        ('import_id', models.CharField(blank=True, max_length=64, null=True)),
                        ('import_payee_name', models.CharField(blank=True, max_length=256, null=True)),
                        ('import_payee_original', models.CharField(blank=True, max_length=256, null=True)),
                        ('debt_transaction_type', models.CharField(blank=True, choices=[('payment', 'Payment'), ('refund', 'Refund'), ('fee', 'Fee'), ('interest', 'Interest'), ('escrow', 'Escrow'), ('balanceAdjustment', 'Balance Adjustment'), ('credit', 'Credit'), ('charge', 'Charge')], max_length=17, null=True)),
                        ('deleted', models.BooleanField()),
                        ('local_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ynabimport')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'ynab_transactions',
                    },
                ),
                migrations.CreateModel(
                    name='BankExpense',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('name', models.CharField(max_length=1024)),
                        ('date', models.DateField()),
                        ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('ynab_transaction_id', models.CharField(blank=True, max_length=256, null=True)),
                        ('paired_on', models.DateTimeField(blank=True, null=True)),
                        ('snoozed_on', models.DateTimeField(blank=True, null=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                        ('file_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bankfileimport')),
                    ],
                    options={
                        'db_table': 'bank_expenses',
                        'constraints': [models.UniqueConstraint(models.F('name'), models.F('date'), models.F('amount'), name='expense-uniqueness-name-date-amount')],
                    },
                ),
            ]
        ),
    ]
