# Generated by Django 5.1.5 on 2025-04-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bankfileimport_ynabcategory_ynabimport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankexpense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bankfileimport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ynabcategory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ynabimport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ynabtransaction',
            name='user',
        ),
    ]
