# Generated by Django 5.2.3 on 2025-07-14 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_note_inbox_alter_inbox_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.banktransaction'),
        ),
        migrations.AlterField(
            model_name='bankfileimport',
            name='file_type',
            field=models.CharField(choices=[('UNICREDIT_BANK_ACCOUNT_CSV_EXPORT', 'Unicredit Bank Account Csv Export'), ('FINECO_BANK_ACCOUNT_XLSX_EXPORT', 'Fineco Bank Account Xlsx Export'), ('UNICREDIT_DEBIT_CARD_CSV_EXPORT', 'Unicredit Debit Card Csv Export'), ('CREDEM_CSV_EXPORT', 'Credem Csv Export')], default='UNICREDIT_BANK_ACCOUNT_CSV_EXPORT', max_length=255),
        ),
    ]
