# Generated by Django 5.2.3 on 2025-07-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_banktransaction_duplicate_of_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='last_selected_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
