# Generated by Django 5.1.5 on 2025-04-14 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_bankexpense_user_remove_bankfileimport_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YnabBudget',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'ynab_budgets',
            },
        ),
        migrations.AddField(
            model_name='ynabcategory',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ynabbudget'),
        ),
        migrations.AddField(
            model_name='ynabimport',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ynabbudget'),
        ),
        migrations.AddField(
            model_name='ynabtransaction',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ynabbudget'),
        ),
    ]
