# Generated by Django 5.1.5 on 2025-03-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_task_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysuggestion',
            name='added_todos',
        ),
        migrations.RemoveField(
            model_name='dailysuggestion',
            name='picked_todos',
        ),
        migrations.RemoveField(
            model_name='dailysuggestionpickedtodo',
            name='suggestion',
        ),
        migrations.RemoveField(
            model_name='dailysuggestionaddedtodo',
            name='suggestion',
        ),
        migrations.AlterUniqueTogether(
            name='dailysuggestionaddedtodo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailysuggestionaddedtodo',
            name='todo',
        ),
        migrations.AlterUniqueTogether(
            name='dailysuggestionpickedtodo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailysuggestionpickedtodo',
            name='todo',
        ),
        migrations.DeleteModel(
            name='Inbox',
        ),
        migrations.RemoveField(
            model_name='waiting',
            name='project',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='project',
        ),
        migrations.RemoveField(
            model_name='update',
            name='project',
        ),
        migrations.DeleteModel(
            name='DailySuggestion',
        ),
        migrations.DeleteModel(
            name='DailySuggestionAddedTodo',
        ),
        migrations.DeleteModel(
            name='DailySuggestionPickedTodo',
        ),
        migrations.DeleteModel(
            name='Waiting',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Update',
        ),
    ]
