# Generated by Django 5.2.3 on 2025-08-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_memory_last_selected_on'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='banktransaction',
            name='expense-uniqueness-name-date-amount',
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.UniqueConstraint(models.F('name'), models.F('date'), models.F('amount'), name='bank-transaction-uniqueness-name-date-amount'),
        ),
    ]
