# Generated by Django 5.1.5 on 2025-04-14 15:38

from django.db import migrations
from settings.base import YNAB_PERSONAL_BUDGET_ID, YNAB_SHARED_BUDGET_ID


def create_default_budget(apps, schema_editor):
   YnabBudget = apps.get_model('core', 'YnabBudget')
   YnabTransaction = apps.get_model('core', 'YnabTransaction')
   YnabCategory = apps.get_model('core', 'YnabCategory')
   YnabImport = apps.get_model('core', 'YnabImport')

   # Get the default budget ID from settings
   personal_budget = YnabBudget.objects.create(
      id=YNAB_PERSONAL_BUDGET_ID,
      name='Personal budget',
   )
   personal_budget.save()

   shared_budget = YnabBudget.objects.create(
      id=YNAB_SHARED_BUDGET_ID,
      name='Shared budget',
   )
   shared_budget.save()

   for transaction in YnabTransaction.objects.all():
      transaction.budget = personal_budget
      transaction.save()

   for category in YnabCategory.objects.all():
      category.budget = personal_budget
      category.save()

   for ynab_import in YnabImport.objects.all():
      ynab_import.budget = personal_budget
      ynab_import.save()


def reverse_migration(apps, schema_editor):
   YnabBudget = apps.get_model('core', 'YnabBudget')
   YnabBudget.objects.all().delete()


class Migration(migrations.Migration):
   dependencies = [
      ('core', '0004_ynabbudget_ynabcategory_budget_ynabimport_budget_and_more'),
   ]

   operations = [
      migrations.RunPython(create_default_budget, reverse_migration)
   ]
