# Generated by Django 5.2.3 on 2025-08-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_memory_last_selected_on'),
    ]

    operations = [
        # Drop existing triggers if they exist
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS bank_transactions_fts_insert;",
            reverse_sql=""
        ),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS bank_transactions_fts_delete;",
            reverse_sql=""
        ),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS bank_transactions_fts_update;",
            reverse_sql=""
        ),
        # Drop existing FTS table if it exists
        migrations.RunSQL(
            "DROP TABLE IF EXISTS bank_transactions_fts;",
            reverse_sql=""
        ),
        # Create the FTS virtual table
        migrations.RunSQL(
            """
            CREATE VIRTUAL TABLE bank_transactions_fts USING fts5(
                id UNINDEXED,
                name,
                date UNINDEXED,
                amount UNINDEXED,
                content='bank_transactions',
                content_rowid='id'
            );
            """,
            reverse_sql="DROP TABLE bank_transactions_fts;"
        ),
        migrations.RunSQL(
            """
            INSERT INTO bank_transactions_fts(id, name, date, amount)
            SELECT id, name, date, amount FROM bank_transactions;
            """,
            reverse_sql=""
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER bank_transactions_fts_insert AFTER INSERT ON bank_transactions BEGIN
                INSERT INTO bank_transactions_fts(id, name, date, amount)
                VALUES (new.id, new.name, new.date, new.amount);
            END;
            """,
            reverse_sql="DROP TRIGGER bank_transactions_fts_insert;"
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER bank_transactions_fts_delete AFTER DELETE ON bank_transactions BEGIN
                INSERT INTO bank_transactions_fts(bank_transactions_fts, id, name, date, amount)
                VALUES ('delete', old.id, old.name, old.date, old.amount);
            END;
            """,
            reverse_sql="DROP TRIGGER bank_transactions_fts_delete;"
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER bank_transactions_fts_update AFTER UPDATE ON bank_transactions BEGIN
                INSERT INTO bank_transactions_fts(bank_transactions_fts, id, name, date, amount)
                VALUES ('delete', old.id, old.name, old.date, old.amount);
                INSERT INTO bank_transactions_fts(id, name, date, amount)
                VALUES (new.id, new.name, new.date, new.amount);
            END;
            """,
            reverse_sql="DROP TRIGGER bank_transactions_fts_update;"
        ),
    ]
