# Generated by Django 5.2.3 on 2025-08-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_banktransaction_expense_uniqueness_name_date_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_on', models.DateTimeField()),
                ('ended_on', models.DateTimeField(blank=True, null=True)),
                ('has_been_interrupted', models.BooleanField(blank=True, default=False, null=True)),
                ('max_duration_minutes', models.IntegerField()),
            ],
            options={
                'db_table': 'time_boxes',
            },
        ),
    ]
