# Generated by Django 5.1.5 on 2025-04-14 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_create_ynab_budgets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ynabcategory',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ynabbudget'),
        ),
        migrations.AlterField(
            model_name='ynabimport',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ynabbudget'),
        ),
        migrations.AlterField(
            model_name='ynabtransaction',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ynabbudget'),
        ),
    ]
