# Generated by Django 5.1.5 on 2025-04-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ynabcategory_budget_alter_ynabimport_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankexpense',
            name='personal_account',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bankfileimport',
            name='personal_account',
            field=models.BooleanField(default=True),
        ),
    ]
