# Generated by Django 5.2.5 on 2025-10-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_inbox_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySuggestion',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
