# Generated by Django 5.2 on 2025-04-27 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_bankfileimport_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ynabtransaction',
            name='account_id',
        ),
        migrations.CreateModel(
            name='YnabAccount',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ynabbudget')),
            ],
            options={
                'db_table': 'ynab_accounts',
            },
        ),
        migrations.AddField(
            model_name='ynabtransaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ynabaccount'),
        ),
    ]
