# Generated by Django 5.2.7 on 2025-10-22 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dailysuggestion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dailysuggestion',
            table='daily_suggestions',
        ),
    ]
