# Generated by Django 5.2 on 2025-05-02 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_ynabtransaction_account_id_ynabaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('iban', models.CharField(max_length=34)),
                ('personal', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='bankexpense',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bankaccount'),
        ),
        migrations.AddField(
            model_name='bankfileimport',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bankaccount'),
        ),
    ]
