# Generated by Django 5.2.7 on 2025-10-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_dailysuggestion_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringSuggestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recurring_suggestions',
            },
        ),
    ]
