# Generated by Django 5.2 on 2025-05-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_bankaccount_bankexpense_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bankaccount',
            table='bank_accounts',
        ),
    ]
