# Generated by Django 5.2.7 on 2025-11-08 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recurringsuggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringsuggestion',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='recurringsuggestion',
            name='recurrences',
        ),
        migrations.RemoveField(
            model_name='recurringsuggestion',
            name='start_date',
        ),
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('daily', 'Daily'), ('day_of_the_week', 'Day of the week'), ('day_of_the_month', 'Day of the month'), ('first_day_of_week_in_month', 'First day of the week in the month'), ('day_of_the_year', 'Day of the year')], default='active', max_length=26)),
                ('day', models.IntegerField()),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.recurringsuggestion')),
            ],
            options={
                'db_table': 'recurrence_rules',
            },
        ),
    ]
