# Generated by Django 5.2 on 2025-05-03 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_bankaccount_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankexpense',
            name='personal_account',
        ),
        migrations.AlterField(
            model_name='bankexpense',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bankaccount'),
        ),
    ]
