# Generated by Django 5.2 on 2025-05-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_bankexpense_personal_account_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankExpense',
            new_name='BankTransaction',
        ),
        migrations.AlterModelTable(
            name='banktransaction',
            table='bank_transactions',
        ),
    ]
