# Generated by Django 5.2 on 2025-05-03 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_bankexpense_banktransaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankfileimport',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='bankfileimport',
            name='personal_account',
        ),
    ]
