# Generated by Django 5.2.8 on 2026-01-01 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_project_parent_alter_recurrencerule_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.RemoveField(
            model_name='bankfileimport',
            name='file_name',
        ),
        migrations.AlterField(
            model_name='bankfileimport',
            name='file_type',
            field=models.CharField(choices=[('UNICREDIT_BANK_ACCOUNT_CSV_EXPORT', 'Unicredit Bank Account Csv Export'), ('FINECO_BANK_ACCOUNT_XLSX_EXPORT', 'Fineco Bank Account Xlsx Export'), ('UNICREDIT_DEBIT_CARD_CSV_EXPORT', 'Unicredit Debit Card Csv Export'), ('CREDEM_CSV_EXPORT', 'Credem Csv Export')], max_length=255),
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.document')),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.AddField(
            model_name='inbox',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.file'),
        ),
    ]
