# Generated by Django 5.2 on 2025-05-04 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_bankfileimport_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ynabcategory',
            options={'verbose_name_plural': 'ynab categories'},
        ),
        migrations.AddField(
            model_name='ynabaccount',
            name='linked_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bankaccount'),
        ),
    ]
