# Generated by Django 5.2.8 on 2026-01-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_document_remove_bankfileimport_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='documents',
            field=models.ManyToManyField(blank=True, to='core.document'),
        ),
    ]
