# Generated by Django 5.2.8 on 2026-01-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_event_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
