# Generated by Django 5.2 on 2025-05-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_ynabcategory_options_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            # Create the FTS virtual table
            """
            CREATE VIRTUAL TABLE bank_transactions_fts USING fts5(id, name);
            """,
            reverse_sql="DROP TABLE IF EXISTS bank_transactions_fts;"
        ),
        migrations.RunSQL(
            # Populate the FTS table with existing data
            """
            INSERT INTO bank_transactions_fts(id, name)
            SELECT id, name FROM bank_transactions;
            """,
            reverse_sql=""
        ),
        migrations.RunSQL(
            # Create INSERT trigger
            """
            CREATE TRIGGER bank_transactions_fts_insert AFTER INSERT ON bank_transactions BEGIN
                INSERT INTO bank_transactions_fts(id, name) VALUES (new.id, new.name);
            END;
            """,
            reverse_sql="DROP TRIGGER IF EXISTS bank_transactions_fts_insert;"
        ),
        migrations.RunSQL(
            # Create UPDATE trigger
            """
            CREATE TRIGGER bank_transactions_fts_update AFTER UPDATE ON bank_transactions BEGIN
                UPDATE bank_transactions_fts SET name = new.name WHERE id = new.id;
            END;
            """,
            reverse_sql="DROP TRIGGER IF EXISTS bank_transactions_fts_update;"
        ),
        migrations.RunSQL(
            # Create DELETE trigger
            """
            CREATE TRIGGER bank_transactions_fts_delete AFTER DELETE ON bank_transactions BEGIN
                DELETE FROM bank_transactions_fts WHERE id = old.id;
            END;
            """,
            reverse_sql="DROP TRIGGER IF EXISTS bank_transactions_fts_delete;"
        ),
    ]
