# Generated by Django 5.2 on 2025-05-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_banktransaction_ynab_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banktransaction',
            old_name='ynab_transaction_id',
            new_name='matched_ynab_transaction',
        ),
    ]
