# Generated by Django 6.0 on 2026-01-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_document_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='content',
            new_name='description',
        ),
    ]
