# Generated by Django 5.2 on 2025-05-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_ynab_transaction_id_banktransaction_matched_ynab_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
