# Generated by Django 5.2.3 on 2025-06-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_note_reviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.FileField(upload_to='memories/')),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'memories',
                'db_table': 'memories',
            },
        ),
    ]
