# Generated by Django 6.0 on 2026-01-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_event_time'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
    ]
