# Generated by Django 6.0 on 2026-05-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_maybe'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='representative_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
