# Generated by Django 6.0 on 2026-05-17 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [('core', '0023_document_representative_date')]

	# The underlying column `category_id` is unchanged: the previous UUIDField
	# named `category_id` and the new ForeignKey named `category` with
	# `db_column='category_id'` map to the same physical column. We only need
	# Django's model state to reflect the new ForeignKey relation, not touch
	# the database — otherwise SQLite would drop and recreate the column,
	# destroying existing category assignments.
	operations = [
		migrations.SeparateDatabaseAndState(
			database_operations=[],
			state_operations=[
				migrations.RemoveField(model_name='ynabtransaction', name='category_id'),
				migrations.AddField(
					model_name='ynabtransaction',
					name='category',
					field=models.ForeignKey(
						blank=True,
						db_column='category_id',
						db_constraint=False,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						to='core.ynabcategory',
					),
				),
			],
		)
	]
