# Generated by Django 6.0 on 2026-06-12 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_ynabtransaction_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predicate',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=256)),
                ('value_type', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'hkm_predicates',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hkm_transactions',
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_index=True, max_length=512)),
                ('predicate', models.CharField(db_index=True, max_length=128)),
                ('object', models.TextField(db_index=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facts', to='core.transaction')),
            ],
            options={
                'db_table': 'hkm_facts',
            },
        ),
        migrations.CreateModel(
            name='Retraction',
            fields=[
                ('fact', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='retraction', serialize=False, to='core.fact')),
                ('reason', models.TextField(blank=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retractions', to='core.transaction')),
            ],
            options={
                'db_table': 'hkm_retractions',
            },
        ),
    ]
