# Generated by Django 6.0 on 2026-06-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_predicate_transaction_fact_retraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredicateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_predicate', models.CharField(db_index=True, max_length=128)),
                ('implied_predicate', models.CharField(max_length=128)),
                ('flip', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'hkm_predicate_rules',
                'constraints': [models.UniqueConstraint(fields=('source_predicate', 'implied_predicate', 'flip'), name='unique_predicate_rule')],
            },
        ),
    ]
