# Generated by Django 6.0 on 2026-07-24 09:36

import django.db.models.deletion
import django.utils.timezone
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_hkm_views'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.IntegerField(choices=[(1, 'Learning'), (2, 'Review'), (3, 'Relearning')], default=1)),
                ('step', models.IntegerField(blank=True, default=0, null=True)),
                ('stability', models.FloatField(blank=True, null=True)),
                ('difficulty', models.FloatField(blank=True, null=True)),
                ('due', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_review', models.DateTimeField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'db_table': 'flashcards',
            },
        ),
        migrations.CreateModel(
            name='FlashcardReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Again'), (2, 'Hard'), (3, 'Good'), (4, 'Easy')])),
                ('reviewed_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.flashcard')),
            ],
            options={
                'db_table': 'flashcard_reviews',
            },
        ),
    ]
