# Generated by Django 6.0 on 2026-07-28 15:57

from django.db import migrations, models

# Both models are unmanaged windows on the SQL views, so these CreateModel operations touch only Django's
# model state — no table is built. The views themselves (including the `id` column InferredFact needs as its
# primary key) are (re)created from core/hkm/views_sql.py by the post_migrate hook in core/apps.py, which runs
# on every migrate, so an existing database picks up the current definitions here.


class Migration(migrations.Migration):
	dependencies = [
		('core', '0027_hkm_views'),
	]

	operations = [
		migrations.CreateModel(
			name='CurrentFact',
			fields=[
				('id', models.IntegerField(primary_key=True, serialize=False)),
				('subject', models.CharField(max_length=512)),
				('predicate', models.CharField(max_length=128)),
				('object', models.TextField()),
			],
			options={
				'db_table': 'hkm_current_facts',
				'managed': False,
			},
		),
		migrations.CreateModel(
			name='InferredFact',
			fields=[
				('id', models.IntegerField(primary_key=True, serialize=False)),
				('subject', models.CharField(max_length=512)),
				('predicate', models.CharField(max_length=128)),
				('object', models.TextField()),
				('origin', models.CharField(max_length=16)),
				('source_fact_id', models.IntegerField()),
			],
			options={
				'db_table': 'hkm_inferred_facts',
				'managed': False,
			},
		),
	]
