# Generated by Django 6.0 on 2026-09-18 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('core', '0030_project_notes_projectupdate'),
	]

	operations = [
		migrations.AlterField(
			model_name='projectupdate',
			name='content',
			field=models.TextField(),
		),
		migrations.AlterField(
			model_name='projectupdate',
			name='project',
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='core.project'
			),
		),
	]
