# Generated by Django 6.0 on 2026-09-18 20:33

from django.db import migrations, models


def backfill_null_notes(apps, schema_editor):
	Project = apps.get_model('core', 'Project')
	Project.objects.filter(notes__isnull=True).update(notes='')


class Migration(migrations.Migration):
	dependencies = [
		('core', '0031_alter_projectupdate_content_and_more'),
	]

	operations = [
		migrations.RunPython(backfill_null_notes, migrations.RunPython.noop),
		migrations.AlterField(
			model_name='project',
			name='notes',
			field=models.TextField(blank=True),
		),
	]
