# Generated by Django 5.1.5 on 2025-02-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='Event',
                ),
                migrations.DeleteModel(
                    name='Note',
                ),
            ],
        )
    ]
