# Generated by Django 5.0.3 on 2024-03-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ynab_reconcile_helper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankexpense",
            name="paired_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bankexpense",
            name="ynab_transaction_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
