# Generated by Django 5.0.6 on 2024-08-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynab_reconcile_helper', '0008_bankfileimport_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankfileimport',
            name='file_type',
            field=models.CharField(choices=[('UNICREDIT_BANK_ACCOUNT_CSV_EXPORT', 'Unicredit Bank Account Csv Export'), ('FINECO_BANK_ACCOUNT_XLSX_EXPORT', 'Fineco Bank Account Xslx Export'), ('UNICREDIT_DEBIT_CARD_CSV_EXPORT', 'Unicredit Debit Card Csv Export')], default='UNICREDIT_BANK_ACCOUNT_CSV_EXPORT', max_length=255),
        ),
    ]
