# Generated by Django 5.1.1 on 2024-09-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
