# Generated by Django 5.1.1 on 2024-10-18 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_todo_valid_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='daily_priority_increase',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='is_valid_order_pray',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.SmallIntegerField(default=0),
        ),
    ]
