# Generated by Django 5.1.1 on 2024-10-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_inbox_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='inbox_after_completion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
