# Generated by Django 5.1.1 on 2024-10-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_todo_last_increase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inbox',
            options={'verbose_name_plural': 'inboxes'},
        ),
    ]
