# Generated by Django 5.1.1 on 2024-10-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_inbox_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
