# Generated by Django 5.1.2 on 2024-10-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_project_options_project_tn_ancestors_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='parent_project',
        ),
    ]
