# Generated by Django 5.1.2 on 2024-10-26 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_project_parent_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='waiting_after_completion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Waiting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('done', 'Done'), ('deleted', 'Deleted')], default='waiting', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.project')),
            ],
        ),
    ]
