# Generated by Django 5.1.3 on 2024-12-15 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_todo_waiting_after_completion_waiting'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySuggestion',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailySuggestionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=0)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.dailysuggestion')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.todo')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('suggestion', 'todo')},
            },
        ),
        migrations.AddField(
            model_name='dailysuggestion',
            name='items',
            field=models.ManyToManyField(through='tasks.DailySuggestionItem', to='tasks.todo'),
        ),
    ]
