# Generated by Django 5.1.3 on 2024-12-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_dailysuggestion_dailysuggestionitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysuggestion',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
