# Generated by Django 5.1.3 on 2024-12-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_dailysuggestion_picked_todos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailysuggestionitem',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='dailysuggestionitem',
            name='order',
        ),
    ]
