# Generated by Django 5.1.3 on 2025-01-01 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_dailysuggestionitem_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailySuggestionItem',
            new_name='DailySuggestionAddedTodo',
        ),
        migrations.RemoveField(
            model_name='dailysuggestion',
            name='items',
        ),
        migrations.RemoveField(
            model_name='dailysuggestion',
            name='picked_todos',
        ),
        migrations.AddField(
            model_name='dailysuggestion',
            name='added_todos',
            field=models.ManyToManyField(related_name='added_todos', through='tasks.DailySuggestionAddedTodo', to='tasks.todo'),
        ),
        migrations.CreateModel(
            name='DailySuggestionPickedTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.dailysuggestion')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.todo')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('suggestion', 'todo')},
            },
        ),
    ]
