# Generated by Django 5.1.3 on 2025-01-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_rename_dailysuggestionitem_dailysuggestionaddedtodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysuggestion',
            name='picked_todos',
            field=models.ManyToManyField(related_name='picked_todos', through='tasks.DailySuggestionPickedTodo', to='tasks.todo'),
        ),
    ]
