# Generated by Django 5.1.5 on 2025-03-01 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_dailysuggestion_picked_todos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dailysuggestion',
            table='daily_suggestions',
        ),
        migrations.AlterModelTable(
            name='dailysuggestionaddedtodo',
            table='daily_suggestion_added_todos',
        ),
        migrations.AlterModelTable(
            name='dailysuggestionpickedtodo',
            table='daily_suggestion_picked_todos',
        ),
        migrations.AlterModelTable(
            name='inbox',
            table='inboxes',
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
        migrations.AlterModelTable(
            name='todo',
            table='todos',
        ),
        migrations.AlterModelTable(
            name='update',
            table='updates',
        ),
    ]
