# Generated by Django 5.1.5 on 2025-02-25 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('martin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
        migrations.AlterModelTable(
            name='note',
            table='notes',
        ),
    ]
