# Generated by Django 5.1.5 on 2025-02-25 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('martin', '0002_alter_event_table_alter_note_table'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='Event',
                ),
                migrations.DeleteModel(
                    name='Note',
                ),
            ],
        ),
    ]
