# Generated by Django 5.0.3 on 2024-04-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0002_bankexpense_paired_on_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="YnabExpense",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("amount", models.FloatField()),
                ("memo", models.CharField(blank=True, max_length=512, null=True)),
                ("approved", models.BooleanField()),
                (
                    "cleared",
                    models.CharField(
                        choices=[
                            ("cleared", "Cleared"),
                            ("uncleared", "Uncleared"),
                            ("reconciled", "Reconciled"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "flag_color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("red", "Red"),
                            ("orange", "Orange"),
                            ("yellow", "Yellow"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("purple", "Purple"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                ("flag_name", models.CharField(blank=True, max_length=64, null=True)),
                ("account_id", models.UUIDField(blank=True, null=True)),
                ("payee_id", models.UUIDField(blank=True, null=True)),
                ("category_id", models.UUIDField(blank=True, null=True)),
                ("transfer_account_id", models.UUIDField(blank=True, null=True)),
                (
                    "transfer_transaction_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "matched_transaction_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("import_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "import_payee_name",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "import_payee_original",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "debt_transaction_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("payment", "Payment"),
                            ("refund", "Refund"),
                            ("fee", "Fee"),
                            ("interest", "Interest"),
                            ("escrow", "Escrow"),
                            ("balanceAdjustment", "Balance Adjustment"),
                            ("credit", "Credit"),
                            ("charge", "Charge"),
                        ],
                        max_length=17,
                        null=True,
                    ),
                ),
                ("deleted", models.BooleanField()),
            ],
        ),
    ]
