# Generated by Django 5.0.4 on 2024-06-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_rename_ynabexpense_ynabtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankexpense',
            name='snoozed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
