# Generated by Django 5.0.4 on 2024-06-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_alter_bankexpense_snoozed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankfileimport',
            name='file_type',
            field=models.CharField(choices=[('UNICREDIT_BANK_ACCOUNT_CSV_EXPORT', 'Unicredit Bank Account Csv Export'), ('FINECO_BANK_ACCOUNT_CSV_EXPORT', 'Fineco Bank Account Csv Export'), ('UNICREDIT_DEBIT_CARD_CSV_EXPORT', 'Unicredit Debit Card Csv Export')], default='UNICREDIT_BANK_ACCOUNT_CSV_EXPORT', max_length=255),
        ),
    ]
