# Generated by Django 5.1.1 on 2024-10-08 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_alter_bankfileimport_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankexpense',
            name='file_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.bankfileimport'),
        ),
        migrations.AlterField(
            model_name='ynabtransaction',
            name='local_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.ynabimport'),
        ),
    ]
