# Generated by Django 5.1.1 on 2024-10-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_ynabcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ynabimport',
            name='server_knowledge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
