# Generated by Django 5.1.2 on 2024-11-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0012_ynabimport_server_knowledge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ynabcategory",
            name="original_category_group_id",
        ),
        migrations.AddField(
            model_name="ynabcategory",
            name="category_group_name",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
    ]
