# Generated by Django 5.1.5 on 2025-02-27 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_remove_ynabcategory_original_category_group_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bankexpense',
            table='bank_expenses',
        ),
        migrations.AlterModelTable(
            name='bankfileimport',
            table='bank_file_imports',
        ),
        migrations.AlterModelTable(
            name='ynabcategory',
            table='ynab_categories',
        ),
        migrations.AlterModelTable(
            name='ynabimport',
            table='ynab_imports',
        ),
        migrations.AlterModelTable(
            name='ynabtransaction',
            table='ynab_transactions',
        ),
    ]
