# Generated by Django 5.1.5 on 2025-03-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0014_alter_bankexpense_table_alter_bankfileimport_table_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='bankfileimport',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='ynabcategory',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='ynabimport',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='ynabtransaction',
                    name='local_import',
                ),
                migrations.RemoveField(
                    model_name='ynabtransaction',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='BankExpense',
                ),
                migrations.DeleteModel(
                    name='BankFileImport',
                ),
                migrations.DeleteModel(
                    name='YnabCategory',
                ),
                migrations.DeleteModel(
                    name='YnabImport',
                ),
                migrations.DeleteModel(
                    name='YnabTransaction',
                ),
            ]
        ),
    ]
